services:
  api:
    build:
      context:
      dockerfile: TechStore.Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/techstore.db
    volumes:
      - techstore_data:/app/data

volumes:
  techstore_data: